
spring:
 datasource:
     url: jdbc:mysql://localhost:3306/system
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
 security:
     user:
      name: testuser
      password: pass001
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true